allowBuilds:
  esbuild: true
  sharp: true
  supabase: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

# pnpm-workspace.yaml
overrides:
  '@supabase/supabase-js': '^2.50.0'
