import 'server-only'

import type { IInviteLinksRepository } from '@/src/application/repositories/invite-links.repository.interface'
import type {
  CreateInviteLinkInput,
  InviteLink,
} from '@/src/entities/models/invite-link'
import type {
  InviteLinkInsert,
  InviteLinkRow,
} from '@/src/infrastructure/supabase/db-types'
import type { TypedSupabaseClient } from '@/src/infrastructure/supabase/types'

const mapRow = (r: InviteLinkRow): InviteLink => ({
  id: r.id,
  token: r.token,
  label: r.label,
  isActive: r.is_active,
  visitCount: r.visit_count,
  lastVisitedAt: r.last_visited_at ? new Date(r.last_visited_at) : null,
  revokedAt: r.revoked_at ? new Date(r.revoked_at) : null,
  createdAt: new Date(r.created_at),
  updatedAt: new Date(r.updated_at),
})

export class SupabaseInviteLinksRepository implements IInviteLinksRepository {
  constructor(private readonly client: TypedSupabaseClient) {}

  async findActiveByToken(token: string): Promise<InviteLink | null> {
    const { data, error } = await this.client
      .from('invite_links')
      .select('*')
      .eq('token', token)
      .eq('is_active', true)
      .maybeSingle()
    if (error) throw new Error(error.message)
    return data ? mapRow(data) : null
  }

  async findActive(): Promise<InviteLink | null> {
    const { data, error } = await this.client
      .from('invite_links')
      .select('*')
      .eq('is_active', true)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle()
    if (error) throw new Error(error.message)
    return data ? mapRow(data) : null
  }

  async list(): Promise<InviteLink[]> {
    const { data, error } = await this.client
      .from('invite_links')
      .select('*')
      .order('created_at', { ascending: false })
    if (error) throw new Error(error.message)
    return (data ?? []).map(mapRow)
  }

  async create(input: CreateInviteLinkInput): Promise<InviteLink> {
    // token + id are generated by column defaults.
    const payload = {
      ...(input.label ? { label: input.label } : {}),
    } satisfies InviteLinkInsert

    const { data, error } = await this.client
      .from('invite_links')
      .insert(payload)
      .select('*')
      .single()
    if (error) throw new Error(error.message)
    return mapRow(data)
  }

  async revokeAllActive(): Promise<number> {
    const { data, error } = await this.client
      .from('invite_links')
      .update({ is_active: false, revoked_at: new Date().toISOString() })
      .eq('is_active', true)
      .select('id')
    if (error) throw new Error(error.message)
    return (data ?? []).length
  }

  async touch(token: string): Promise<void> {
    const { error } = await this.client.rpc('touch_invite_link', {
      p_token: token,
    })
    if (error) throw new Error(error.message)
  }
}
